[tool.poetry]
name = "py-power-meter-monitor"
version = "0.1.1"
description = ""
authors = ["Felix Stürmer <stuermer@weltenwort.de>"]
license = "MIT"
include = ["etc/default-config.toml", "etc/logarex-config.toml"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.3.2"
pydantic = "^1.8.1"
tomlkit = "^0.7.0"
pyserial-asyncio = "^0.5"
asyncio-mqtt = "^0.8.1"
async-timeout = "^3.0.1"
aioserial = "^1.3.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
pytest = "^6.2.2"
pytest-asyncio = "^0.14.0"
pytest-watch = "^4.2.0"
pre-commit = "^2.11.1"
hypothesis = "^6.8.4"

[tool.poetry.scripts]
py-power-meter-monitor = "py_power_meter_monitor.cli:app"

[tool.black]
disable = ["C0330", "C0326"]
max-line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
