name: Linting

on:
  push:
    branches: [main]
  pull_request:

env:
  DEFAULT_PYTHON: 3.9

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Set up poetry
        uses: Gr1N/setup-poetry@v8

      - name: Enable caching
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install Python modules
        run: |
          poetry install

      - name: Run pre-commit on all files
        run: |
          poetry run pre-commit run --all-files --show-diff-on-failure --color=always
